# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [3]:
url = 'https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/student-mat.csv'
df = pd.read_csv(url)
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [6]:
stud_alcohol = df.loc[: , "school":"guardian"]
stud_alcohol.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father

### Step 5. Create a lambda function that will capitalize strings.

In [8]:
capitalizer = lambda x: x.capitalize()

### Step 6. Capitalize both Mjob and Fjob

In [10]:
stud_alcohol['Mjob'].apply(capitalizer)
stud_alcohol['Fjob'].apply(capitalizer)

0       Teacher
1         Other
2         Other
3      Services
4         Other
         ...
390    Services
391    Services
392       Other
393       Other
394     At_home
Name: Fjob, Length: 395, dtype: object

### Step 7. Print the last elements of the data set.

In [13]:
print(stud_alcohol.tail())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     reason guardian
390  course    other
391  course   mother
392  course    other
393  course   mother
394  course   father

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [14]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [18]:
def legal_drinker(age):
    return age > 17

In [19]:
stud_alcohol['legal_drinker'] = stud_alcohol['age'].apply(legal_drinker)
print("\nStep 10. DataFrame with 'legal_drinker':\n", stud_alcohol.head())

Step 10. DataFrame with 'legal_drinker':
   school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher
1     GP   F   17       U     GT3       T     1     1  at_home     other
2     GP   F   15       U     LE3       T     1     1  at_home     other
3     GP   F   15       U     GT3       T     4     2   health  services
4     GP   F   16       U     GT3       T     3     3    other     other

   reason guardian  legal_drinker
0  course   mother           True
1  course   father          False
2   other   mother          False
3    home   mother          False
4    home   father          False

### Step 10. Multiply every number of the dataset by 10.
##### I know this makes no sense, don't forget it is just an exercise

In [20]:
def multiply_by_10(x):
    if isinstance(x, (int, float)):  # Check if numeric
        return x * 10
    return x  # Return original value if not numeric

In [22]:
for col in stud_alcohol.columns:
    stud_alcohol[col] = stud_alcohol[col].apply(multiply_by_10)
stud_alcohol.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,1800,U,GT3,A,400,400,at_home,teacher,course,mother,100
1,GP,F,1700,U,GT3,T,100,100,at_home,other,course,father,0
2,GP,F,1500,U,LE3,T,100,100,at_home,other,other,mother,0
3,GP,F,1500,U,GT3,T,400,200,health,services,home,mother,0
4,GP,F,1600,U,GT3,T,300,300,other,other,home,father,0